/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConfigResponse"];
                        "application/json": components["schemas"]["ConfigResponse"];
                        "text/json": components["schemas"]["ConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Images/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UploadedImage"];
                        "application/json": components["schemas"]["UploadedImage"];
                        "text/json": components["schemas"]["UploadedImage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductSummary"][];
                        "application/json": components["schemas"]["ProductSummary"][];
                        "text/json": components["schemas"]["ProductSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDetail"];
                        "application/json": components["schemas"]["ProductDetail"];
                        "text/json": components["schemas"]["ProductDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Products/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sort?: string;
                    rating?: number;
                    hasPhotos?: boolean;
                    cursor?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReviewsPage"];
                        "application/json": components["schemas"]["ReviewsPage"];
                        "text/json": components["schemas"]["ReviewsPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitReviewRequest"];
                    "text/json": components["schemas"]["SubmitReviewRequest"];
                    "application/*+json": components["schemas"]["SubmitReviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcceptedResponse"];
                        "application/json": components["schemas"]["AcceptedResponse"];
                        "text/json": components["schemas"]["AcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EditReviewRequest"];
                    "text/json": components["schemas"]["EditReviewRequest"];
                    "application/*+json": components["schemas"]["EditReviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcceptedResponse"];
                        "application/json": components["schemas"]["AcceptedResponse"];
                        "text/json": components["schemas"]["AcceptedResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcceptedResponse"];
                        "application/json": components["schemas"]["AcceptedResponse"];
                        "text/json": components["schemas"]["AcceptedResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reviews/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VoteRequest"];
                    "text/json": components["schemas"]["VoteRequest"];
                    "application/*+json": components["schemas"]["VoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcceptedResponse"];
                        "application/json": components["schemas"]["AcceptedResponse"];
                        "text/json": components["schemas"]["AcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptedResponse: {
            workflowId: string;
            status: string;
        };
        ConfigResponse: {
            turnstileSiteKey: string;
        };
        EditReviewRequest: {
            /** Format: int32 */
            rating: number;
            title: string;
            body: string;
            imageUrls?: string[] | null;
        };
        ProductDetail: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            description: string;
            imageUrl?: string;
            /** Format: double */
            averageRating: number;
            /** Format: int32 */
            reviewCount: number;
            /** Format: uuid */
            myReviewId?: string | null;
        };
        ProductSummary: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            imageUrl?: string;
            /** Format: double */
            averageRating: number;
            /** Format: int32 */
            reviewCount: number;
        };
        ReviewItem: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            productId: number;
            /** Format: uuid */
            authorId: string;
            authorName: string;
            /** Format: int32 */
            rating: number;
            title: string;
            body: string;
            imageUrls: string[];
            /** Format: int32 */
            score: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            myVote?: number | null;
            mine: boolean;
        };
        ReviewsPage: {
            items: components["schemas"]["ReviewItem"][];
            nextCursor?: string | null;
        };
        SubmitReviewRequest: {
            /** Format: int64 */
            productId: number;
            /** Format: int32 */
            rating: number;
            title: string;
            body: string;
            imageUrls?: string[] | null;
            turnstileToken: string;
        };
        UploadedImage: {
            url: string;
        };
        VoteRequest: {
            /** Format: int32 */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
